---
title: "Shiny and Reproducible Documentation"
author: "Yash Punjabi"
date: "26/09/2020"
output: html_document
---



## Project Goal

This peer assessed assignment has two parts.First, you will create a Shiny application and deploy it on Rstudio's servers.Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.

## Steps To perform

1. Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user will need to get started using your application.
2. Deploy the application on Rstudio's shiny server
3. Share the application link by pasting it into the provided text box
4. Share your server.R and ui.R code on github

## How to use the application

Using the data provided by mtcars dataset, we plot Miles per Gallon with different input variables Cylinder,Transmission, Gears

The application is running on
()

Here is the github repository link containing code
()

## Plot

```{r mtcars,results='hide'}
mpgData <- mtcars
mpgData$am <- factor(mpgData$am, labels = c("Automatic", "Manual"))
boxplot(mpg ~ cyl, data = mpgData) # For cylinder
boxplot(mpg ~ am, data = mpgData) # Transmission
boxplot(mpg ~ gear, data = mpgData) # Gear
```
